### ISSUE TITLE
Models hulk

### ISSUE THREAD

**Issue by smokedark** [Drakunovu/jailbreak-bugtracker#2]
Los models de ct y tt y hulk se bugean, las manos de hulk se ve como el cuchillo normal y no las manos de hulk

**Comment by Drakunovu** [comment]
Arreglado, pero falta lo del cuchillo.

**Comment by Drakunovu** [comment]
Cuchillos arreglado, falta probarlo.

**Comment by Drakunovu** [comment]
Manos arregladas, pero cuando se utiliza vía comando de administración no se ven las manos...
